### ISSUE TITLE
Add automatic code formatting to (pre) commit

### ISSUE THREAD

**Issue by knarfnitram** [imcs-compsim/meshpy#104]
For most of the software projects I am currently working with, automatic code formatting on committing is standard.
Of course, one can shift this duty to the IDE(click on save, plugins etc.), but since the CI is already checking whether the code is formatted with `black`.  I think it would be reasonable to add it in a pre commit as well. 

Are there any objections to add code formatting on (pre) commit ?

**Comment by isteinbrecher** [comment]
Sounds like a good idea!
