### ISSUE TITLE
Question: Failing actions on forks

### ISSUE THREAD

**Issue by davidrudlstorfer** [imcs-compsim/meshpy#155]
I have a question regarding the MeshPy workflow:

The development is done through forks -> naturally the actions are executed within the fork as well. Specifically, the selfhosted action running with cubitpy and the deployment of the website fail within my fork.

Each time this action fails I get an email. Did you just disable the actions on your fork? Or is there another workaround?

Thanks for your input!

**Comment by isteinbrecher** [comment]
I personally disabled the actions on my fork. One other workaround I can think of, is to add an `if` clause containing the full repository name `${{ github.repository }} == "imcs-compsim/meshpy"`.

**Comment by davidrudlstorfer** [comment]
Thanks for your input on that matter @isteinbrecher!

I also simply disabled the actions on my fork - I thought there could be a simpler way to just disable it for all forks.

**Comment by davidrudlstorfer** [comment]
Unfortunately, I have a question regarding the actions in forks again:

I disabled the actions in my personal fork settings like this:

<img width="803" alt="Screenshot 2024-12-19 at 08 27 25" src="https://github.com/user-attachments/assets/e0296ddf-0e39-45d1-80d3-7abdc4b20034" />

Since then (3 days ago) I get multiple emails a day that the actions are failing within my fork:

<img width="572" alt="Screenshot 2024-12-19 at 08 29 09" src="https://github.com/user-attachments/assets/998f7fe7-beec-4397-a0e2-f35f7f361cce" />


@isteinbrecher do you have any clue what could be the problem?

**Comment by isteinbrecher** [comment]
I think that could be a backlog of jobs waiting to be executed on self hosted runners. They have a couple of days until they run into a time out, so my guess would be those are ones that were started before you switched your settings. Maybe check if you still have any pending actions. So the problem should solve itself in a couple of days. If so, please close the PR, otherwise lets find a solution that works.
