### ISSUE TITLE
Are empty sections within the .dat file necessary?

### ISSUE THREAD

**Issue by davidrudlstorfer** [imcs-compsim/meshpy#70]
When creating .dat files with MeshPy certain sections of the created .dat file stay empty most of the times.

For example for all pure structure cases the `FLUID ELEMENTS` section stays empty.

In my opinion these empty sections do not need to be written out if there are no elements of this specific type within the current problem setup.

This could be solved with a simple addition within `meshpy/inputfile.py`. Just add

```python

if len(data_list) == 0:
    return
```

at the beginning of the `get_section_dat`.

If this would be possible - let me know and I open a PR (and adjust all reference files)

**Comment by isteinbrecher** [comment]
Sounds good to me!
